# Generated by Django 5.0.7 on 2024-08-13 15:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_hiddenpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_key',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
