# Generated by Django 5.0.7 on 2024-08-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_key',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
