# Generated by Django 5.0.7 on 2024-08-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_avatar_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='background_pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='background_pic_key',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
