# Generated by Django 5.0.7 on 2024-08-15 19:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_blockeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_key',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
