# Generated by Django 5.0.7 on 2024-08-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_avatar_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar_key',
            field=models.CharField(max_length=255),
        ),
    ]
