# Generated by Django 5.0.7 on 2024-08-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0002_vlog_vlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlog',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vlog',
            name='vlog',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
