# Generated by Django 5.0.7 on 2024-08-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0003_alter_vlog_duration_alter_vlog_vlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlog',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
