# Generated by Django 5.0.7 on 2024-08-07 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0004_vlog_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlog',
            name='vlog',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])]),
        ),
    ]
