# Generated by Django 5.0.7 on 2024-08-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0005_alter_vlog_vlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
