# Generated by Django 5.0.7 on 2024-08-11 19:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0006_alter_vlog_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='video',
            new_name='vlog',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='video',
            new_name='vlog',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('vlog', 'user')},
        ),
    ]
