# Generated by Django 5.0.7 on 2024-08-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0007_rename_video_comment_vlog_rename_video_like_vlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlog',
            name='vlog',
        ),
        migrations.AddField(
            model_name='vlog',
            name='vlog_key',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
