# Generated by Django 5.0.7 on 2024-08-16 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0008_remove_vlog_vlog_vlog_vlog_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='VlogProcessingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vlog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_task', to='vlogs.vlog')),
            ],
        ),
    ]
