# Generated by Django 5.0.7 on 2024-08-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0009_vlogprocessingtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlog',
            name='processing_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
